import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <aside className="bg-red-100 w-40 text-center p-2">
            <div>
              <h1>NavBar</h1>
            </div>
            <nav>
              <Link href="/">Home</Link>
            </nav>
            <nav>
              <Link href="/main">หน้าแรก</Link>
            </nav>
          </aside>

          <main className="flex-1 bg-gray-500">
            <div>
              {children}
            </div>
          </main>
        </div>
      </body>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
    </html>
  );
}
