import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import LogoutButton from "./logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <div className="flex min-h-screen">
            <aside className="bg-slate-900 text-white w-52 p-6 text-center shadow-lg">
              <div className="mb-8">
                <h1 className="text-2xl font-bold mb-2">รายการต่างๆ</h1>
                <h2 className="text-slate-300">ชื่อผู้ใช้  : {session?.user?.email ? session?.user?.email : 'anon'}</h2>
              </div>
              <nav className="space-y-2">
                <Link
                  href="/"
                  className="block px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-colors"
                >
                  Home
                </Link>
                {
                  session?.user?.email
                    ?
                    <LogoutButton />
                    :
                    <Link href="/login" className="block px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 rounded-lg">Login</Link>
                }
                <Link
                  href="/facedetect"
                  className="block px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
                >
                  Face Detect
                </Link>
                <Link
                  href="/main"
                  className="block px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 rounded-lg"
                >
                  ข้อมูลคนหาย
                </Link>
                {
                  session?.user?.email
                  &&
                  <Link
                    href="/addPerson"
                    className="block px-4 py-2 bg-green-600 text-white hover:bg-green-700 rounded-lg"
                  >
                    เพิ่มข้อมูล
                  </Link>

                }
              </nav>

            </aside>

            <main className="flex-1">
              <div>
                {children}
              </div>
            </main>
          </div>
        </SessionProvider>
      </body>

      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
    </html>
  );
}
