import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import LogoutButton from "./logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <div className="flex min-h-screen">
            <aside className="bg-red-100 w-40 text-center p-2">
              <div className="p-2">
                <h1 className="text-xl font-bold">รายการต่างๆ</h1>
                <h2>ชื่อผู้ใช้  : {session?.user?.email ? session?.user?.email : 'anon'}</h2>
              </div>
              <nav className="p-2">
                <Link href="/" className="px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 rounded-lg">Home</Link>
              </nav>

              <nav className="p-2">
                {
                  session?.user?.email
                    ? 
                    <LogoutButton />
                    :
                    <Link href="/login" className="px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 rounded-lg">Log in</Link>
                }  
              </nav>
              <nav className="p-2">
                <Link href="/main" className="px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 rounded-lg">ข้อมูลคนหาย</Link>
              </nav>
            </aside>

            <main className="flex-1">
              <div>
                {children}
              </div>
            </main>
          </div>
        </SessionProvider>
      </body>

      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
    </html>
  );
}
